# Cf. https://github.com/pyTooling/Actions/#reusable-workflows
name: Build and Test
on:
  workflow_call:
    inputs:
      matrix-os-version:
        description: "JSON array as a string, a list of operating systems for the matrix build"
        required: true
        type: string
      matrix-python-version:
        description: "JSON array as a string, a list of Python versions for the matrix build"
        required: true
        type: string
      poetry-version:
        description: "Version of Poetry to use for the build (>=1.2.0)"
        required: true
        type: string
      poetry-cache-venv:
        description: "Whether to cache the Poetry virtualenv"
        required: false
        type: boolean
        default: true
      poetry-cache-install:
        description: "Whether to cache the Poetry install"
        required: false
        type: boolean
        default: true
      test-suite-command:
        description: "Shell command used to execute the test suite"
        required: false
        type: string
        default: "inv test.suite"
      timeout-minutes:
        description: "Job timeout in minutes"
        required: false
        type: number
        default: 30
jobs:
  build:
    strategy:
      matrix:
        os: "${{ fromJson(inputs.matrix-os-version) }}"
        python: "${{ fromJson(inputs.matrix-python-version) }}"
        exclude:
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: 3.8
          - os: macos-latest
            python: 3.9
          - os: macos-latest
            python: 3.10
          - os: windows-latest
            python: 3.7
          - os: windows-latest
            python: 3.8
          - os: windows-latest
            python: 3.9
          - os: windows-latest
            python: 3.10

    defaults:
      run:
        shell: bash
    runs-on: "${{ matrix.os }}"
    timeout-minutes: "${{ inputs.timeout-minutes }}"
    steps:
#      - if: ${{ runner.os == 'Windows' }}
#        name: Use GNU tar
#        shell: cmd
#        run: |
#          echo "Adding GNU tar to PATH"
#          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: "poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ inputs.poetry-version }}-0"
        if: ${{ inputs.poetry-cache-install && runner.os != 'Windows' }}
      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        if: ${{ inputs.poetry-cache-venv && runner.os != 'Windows' }}
      - name: Install dependencies
        shell: bash
        run: |
          # Install dependencies
          poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install project
        shell: bash
        run: |
          # Install project
          poetry install --no-interaction
      - name: Run test suite
        shell: bash
        run: |
          # Run the test suite
          source $VENV
          ${{ inputs.test-suite-command }}
      - name: Upload coverage data to coveralls.io
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COVERALLS_FLAG_NAME: "${{ runner.os }}-python${{ matrix.python }}"
          COVERALLS_PARALLEL: true
        run: |
          # Upload coverage data to coveralls.io
          poetry run coveralls --service=github
  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      shell: bash
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        # Indicate completion to coveralls.io
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
